<?php
get_template_part('/inc/customizer/sanitize');
get_template_part('/inc/customizer/enqueue');
get_template_part('/inc/customizer/controls-register');
get_template_part('/inc/customizer/options/customizer-header');
get_template_part('/inc/customizer/options/customizer-general');
get_template_part('/inc/customizer/options/customizer-footer');
get_template_part('/inc/customizer/options/customizer-typography');
get_template_part('/inc/customizer/options/customizer-go-pro');
get_template_part('/inc/customizer/sections-homepage/section-slider');
get_template_part('/inc/customizer/sections-homepage/section-prod_recent');
get_template_part('/inc/customizer/sections-homepage/section-banner');
get_template_part('/inc/customizer/sections-homepage/section-testimonial');
get_template_part('/inc/customizer/sections-homepage/section-blog');